#Geometric objects. 
#bargraph geom => geom_bar()
#linegraph geom => geom_line()
#boxplot geom => geom_boxplot()
#smoothgraph => geom_smooth()

#using geom_smooth()
ggplot(data = mpg) +
    geom_smooth(mapping = aes(displ, hwy))

#adding linetype to geom_smooth() to differentiate variable classes
ggplot(mpg) +
    geom_smooth(aes(displ, hwy, linetype = drv))

#add color to the linetype attribute for easier differentiation of variable groups

ggplot(mpg) +
    geom_smooth(aes(displ, hwy, linetype = class, color = class))

ggplot(mpg) +
    geom_smooth(aes(displ, hwy, linetype = drv, color = drv))

#Grouping variable classes/groups
#Downside: classes can't be differentiated.

ggplot(data = mpg) +
    geom_smooth(mapping = aes(displ, hwy, group = drv))

#Differentiating variable classes without legend.
#set geom_smooth to show.legend = FALSE 
#and TRUE to show the legend.
#Note: Legend necessary to differentiate variable classes
ggplot(mpg) +
    geom_smooth(aes(displ, hwy, color = drv), show.legend = FALSE)
ggplot(data = mpg) +
    geom_smooth(mapping = aes(displ, hwy, color = drv), show.legend = TRUE)

#Displaying multiple geoms
#add multiple geom functions to ggplot()
ggplot(data = mpg) +
    geom_point(mapping = aes(displ, hwy, color = class)) +
    geom_smooth(mapping = aes(displ, hwy, linetype = class, color = class))

#reducing repetition in creating multiple geom function.
# include similar mappings in the ggplot()
#below code similar to the preceding one.
ggplot(data = mpg, mapping = aes(displ, hwy, color = class)) +
    geom_point() +
    geom_smooth(aes(linetype = class))


#The graphs generated by the 2 codes below are similar
ggplot() +
    geom_point(data = mpg, mapping = aes(displ, hwy)) +
    geom_smooth(data = mpg, mapping = aes(displ, hwy))

ggplot(data = mpg, mapping = aes(displ, hwy)) +
    geom_point() +
    geom_smooth()

#Exercise. 
#Graphs already provided. Write the code to generate similar graphs

#installed "cowplot" package to use the plot_grid() function
install.packages('cowplot')
library(cowplot)
p1 <- ggplot(data = mpg, mapping = aes(displ, hwy)) +
    geom_point(stroke = 1) +
    geom_smooth(se = FALSE)
    

#group drv variable 
p2 <- ggplot(data = mpg, mapping = aes(displ, hwy)) +
    
    geom_point(stroke = 1) +
    geom_smooth(aes(group = drv), se = FALSE)
p2

#Color the variable drv of mpg dataset    
p3 <- ggplot(data = mpg, mapping = aes(displ, hwy, color = drv)) +
    geom_point(stroke = 1) +
    geom_smooth(se = FALSE)
p3

#use filter method to specify variable class
p4 <- ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
    geom_point(mapping = aes(color=drv), stroke = 1) +
    geom_smooth(se = FALSE)
p4

p5 <- ggplot(data = mpg, mapping = aes(displ, hwy, color = drv)) +
    geom_point(stroke = 1) +
    geom_smooth(mapping = aes(linetype = drv), se = FALSE)
p5

p6 <- ggplot(data = mpg, mapping = aes(displ, hwy, color = drv)) +
    geom_point(stroke = 1)
p6

#plotting the graphs in a grid using plot_grid() method
plot_grid(p1, p2, p3, p4, p5, p6, labels = c(1, 2, 3, 4, 5, 6), label_size = 12, ncol = 2, nrow = 3)